# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011
# Sasuke(Kyohei MORIYAMA) <>, 2015
# *pokotan-in-the-sky*  <>, 2012
# Tom Fifield <tom@openstack.org>, 2013
# Tomoyuki KATO <tomo@dream.daynight.jp>, 2013
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: nova VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2023-12-18 23:50+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-04-12 06:06+0000\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 4.3.3\n"
"Language-Team: Japanese\n"

#, python-format
msgid "%(address)s is not a valid IP v4/6 address."
msgstr "%(address)s が有効な IP v4/6 アドレスではありません。"

#, python-format
msgid ""
"%(binary)s attempted direct database access which is not allowed by policy"
msgstr ""
"%(binary)s が直接データベースへアクセスしようとしましたが、これはポリシーで許"
"可されていません"

#, python-format
msgid "%(cidr)s is not a valid IP network."
msgstr "%(cidr)s や有効な IP ネットワークではありません。"

#, python-format
msgid "%(field)s should not be part of the updates."
msgstr "%(field)s を更新に含めることはできません。"

#, python-format
msgid "%(memsize)d MB of memory assigned, but expected %(memtotal)d MB"
msgstr ""
"%(memsize)d MB のメモリーが割り当てられていますが、%(memtotal)d MB が期待され"
"ていました"

#, python-format
msgid "%(path)s is not on local storage: %(reason)s"
msgstr "%(path)s はローカルストレージ上にありません: %(reason)s"

#, python-format
msgid "%(path)s is not on shared storage: %(reason)s"
msgstr "%(path)s は共有ストレージ上にありません: %(reason)s"

#, python-format
msgid "%(total)i rows matched query %(meth)s, %(done)i migrated"
msgstr "%(total)i 行がクエリー %(meth)s に合致し、%(done)i が移行しました"

#, python-format
msgid "%(type)s hypervisor does not support PCI devices"
msgstr "%(type)s ハイパーバイザーは PCI デバイスをサポートしていません"

#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr ""
"%(workers)s の %(worker_name)s 値が無効です。0 より大きい値にしなければなりま"
"せん"

#, python-format
msgid "%s does not support disk hotplug."
msgstr "%s ではディスクのホットプラグはサポートされていません。"

#, python-format
msgid "%s format is not supported"
msgstr "%s 形式はサポートされていません"

#, python-format
msgid "%s is not supported."
msgstr "%s はサポートされていません。"

#, python-format
msgid "%s must be either 'MANUAL' or 'AUTO'."
msgstr "%s は 'MANUAL' または 'AUTO' のいずれかでなければいけません。"

#, python-format
msgid "'%(other)s' should be an instance of '%(cls)s'"
msgstr "'%(other)s' は'%(cls)s' のインスタンスである必要があります"

msgid "'qemu-img info' parsing failed."
msgstr "'qemu-img info' の解析に失敗しました。"

#, python-format
msgid "'rxtx_factor' argument must be a float between 0 and %g"
msgstr ""
"'rxtx_factor' 引数は 0 から %g の範囲内の浮動小数点数でなければなりません"

#, python-format
msgid "A NetworkModel is required in field %s"
msgstr "フィールド %s に NetworkModel が必要です"

#, python-format
msgid ""
"API Version String %(version)s is of invalid format. Must be of format "
"MajorNum.MinorNum."
msgstr ""
"API バージョン文字列 %(version)s の形式が無効です。形式は MajorNum.MinorNum "
"でなければなりません。"

#, python-format
msgid "API version %(version)s is not supported on this method."
msgstr "API バージョン %(version)s はこのメソッドではサポートされていません。"

msgid "Access list not available for public flavors."
msgstr "パブリックフレーバーではアクセスリストを使用できません。"

#, python-format
msgid "Action %s not found"
msgstr "アクション %s が見つかりません"

#, python-format
msgid ""
"Action for request_id %(request_id)s on instance %(instance_uuid)s not found"
msgstr ""
"インスタンス %(instance_uuid)s に対する request_id %(request_id)s のアクショ"
"ンが見つかりません"

#, python-format
msgid "Action: '%(action)s', calling method: %(meth)s, body: %(body)s"
msgstr "アクション: '%(action)s'、呼び出しメソッド: %(meth)s、本文: %(body)s"

#, python-format
msgid "Add metadata failed for aggregate %(id)s after %(retries)s retries"
msgstr ""
"アグリゲート %(id)s にメタデータを追加しようと %(retries)s 回再試行しました"
"が、追加できませんでした"

#, python-format
msgid "Aggregate %(aggregate_id)s already has host %(host)s."
msgstr "アグリゲート %(aggregate_id)s には既にホスト %(host)s があります。"

#, python-format
msgid "Aggregate %(aggregate_id)s could not be found."
msgstr "アグリゲート %(aggregate_id)s が見つかりませんでした。"

#, python-format
msgid "Aggregate %(aggregate_id)s has no host %(host)s."
msgstr "アグリゲート %(aggregate_id)s にはホスト %(host)s がありません。"

#, python-format
msgid "Aggregate %(aggregate_id)s has no metadata with key %(metadata_key)s."
msgstr ""
"アグリゲート %(aggregate_id)s にはキー %(metadata_key)s を持つメタデータはあ"
"りません。"

#, python-format
msgid "Aggregate %(aggregate_name)s already exists."
msgstr "アグリゲート %(aggregate_name)s は既に存在します。"

#, python-format
msgid "Aggregate %s does not support empty named availability zone"
msgstr "アグリゲート %s は空の名前のアベイラビリティーゾーンをサポートしません"

#, python-format
msgid "An invalid 'name' value was provided. The name must be: %(reason)s"
msgstr ""
"無効な 'name' の値が提供されました。名前は以下である必要があります: "
"%(reason)s"

msgid "An unknown error has occurred. Please try your request again."
msgstr "未知のエラーが発生しました。再度リクエストを実行してください。"

msgid "An unknown exception occurred."
msgstr "不明な例外が発生しました。"

#, python-format
msgid "Architecture name '%(arch)s' is not recognised"
msgstr "アーキテクチャー名 '%(arch)s' は認識できません"

#, python-format
msgid "Architecture name '%s' is not valid"
msgstr "アーキテクチャー名 '%s' が有効ではありません"

#, python-format
msgid ""
"Attempt to consume PCI device %(compute_node_id)s:%(address)s from empty pool"
msgstr ""
"空のプールから PCI デバイス %(compute_node_id)s:%(address)s を取り込んでみて"
"ください"

msgid "Attempted overwrite of an existing value."
msgstr "既存の値を上書きしようとしました。"

#, python-format
msgid "Attribute not supported: %(attr)s"
msgstr "この属性はサポートされていません: %(attr)s"

#, python-format
msgid "Bad network format: missing %s"
msgstr "ネットワークの形式が正しくありません。%s がありません"

msgid "Bad networks format"
msgstr "ネットワークの形式が正しくありません"

#, python-format
msgid "Bad networks format: network uuid is not in proper format (%s)"
msgstr ""
"ネットワークの形式が正しくありません。ネットワーク UUID が適切な形式になって"
"いません (%s)"

#, python-format
msgid "Bad prefix for network in cidr %s"
msgstr "CIDR %s 内のネットワークでは無効なプレフィックス"

#, python-format
msgid ""
"Binding failed for port %(port_id)s, please check neutron logs for more "
"information."
msgstr ""
"ポート %(port_id)s でバインドが失敗しました。詳細情報については neutron のロ"
"グを確認してください。"

msgid "Blank components"
msgstr "空白コンポーネント"

msgid ""
"Blank volumes (source: 'blank', dest: 'volume') need to have non-zero size"
msgstr ""
"ブランクのボリューム (ソース: 'blank'、宛先: 'volume') にはゼロでないサイズを"
"設定する必要があります"

#, python-format
msgid "Block Device %(id)s is not bootable."
msgstr "ブロックデバイス %(id)s がブート可能ではありません。"

#, python-format
msgid ""
"Block Device Mapping %(volume_id)s is a multi-attach volume and is not valid "
"for this operation."
msgstr ""
"ブロックデバイスマッピング %(volume_id)s は複数の接続を持つボリュームであり、"
"この処理には有効ではありません。"

msgid "Block Device Mapping cannot be converted to legacy format. "
msgstr "ブロックデバイスマッピングを以前の形式に変換することはできません。"

msgid "Block Device Mapping is Invalid."
msgstr "ブロックデバイスマッピングが無効です。"

#, python-format
msgid "Block Device Mapping is Invalid: %(details)s"
msgstr "ブロックデバイスマッピングが無効です: %(details)s"

msgid ""
"Block Device Mapping is Invalid: Boot sequence for the instance and image/"
"block device mapping combination is not valid."
msgstr ""
"ブロックデバイスマッピングが無効です。指定されたインスタンスとイメージ/ブロッ"
"クデバイスマッピングの組み合わせでのブートシーケンスは無効です。"

msgid ""
"Block Device Mapping is Invalid: You specified more local devices than the "
"limit allows"
msgstr ""
"ブロックデバイスマッピングが無効です。制限で許可されているよりも多くのローカ"
"ルデバイスが指定されました。"

#, python-format
msgid "Block Device Mapping is Invalid: failed to get image %(id)s."
msgstr ""
"ブロックデバイスマッピングが無効です。イメージ %(id)s の取得に失敗しました。"

#, python-format
msgid "Block Device Mapping is Invalid: failed to get snapshot %(id)s."
msgstr ""
"ブロックデバイスマッピングが無効です。スナップショット %(id)s の取得に失敗し"
"ました。"

#, python-format
msgid "Block Device Mapping is Invalid: failed to get volume %(id)s."
msgstr ""
"ブロックデバイスマッピングが無効です。ボリューム %(id)s の取得に失敗しまし"
"た。"

msgid "Block migration can not be used with shared storage."
msgstr ""
"ブロックマイグレーションを使用するときに、共有ストレージを使用することはでき"
"ません。"

msgid "Boot index is invalid."
msgstr "boot インデックスが無効です。"

#, python-format
msgid "Build of instance %(instance_uuid)s aborted: %(reason)s"
msgstr "インスタンス %(instance_uuid)s の作成は打ち切られました: %(reason)s"

#, python-format
msgid "Build of instance %(instance_uuid)s was re-scheduled: %(reason)s"
msgstr ""
"インスタンス %(instance_uuid)s の作成は再スケジュールされました: %(reason)s"

#, python-format
msgid "BuildRequest not found for instance %(uuid)s"
msgstr "インスタンス %(uuid)s に関する BuildRequest が見つかりません"

msgid "CPU and memory allocation must be provided for all NUMA nodes"
msgstr ""
"CPU とメモリーの割り当ては、すべての NUMA ノードに指定しなければなりません"

#, python-format
msgid ""
"CPU doesn't have compatibility.\n"
"\n"
"%(ret)s\n"
"\n"
"Refer to %(u)s"
msgstr ""
"CPU に互換性がありません。\n"
"\n"
"%(ret)s\n"
"\n"
"%(u)s を参照"

#, python-format
msgid "CPU number %(cpunum)d is assigned to two nodes"
msgstr "CPU 番号 %(cpunum)d は 2 つのノードに割り当てられています"

#, python-format
msgid "CPU number %(cpunum)d is larger than max %(cpumax)d"
msgstr "CPU 番号 %(cpunum)d は最大値 %(cpumax)d を超えています"

#, python-format
msgid "CPU number %(cpuset)s is not assigned to any node"
msgstr "CPU 番号 %(cpuset)s はノードに割り当てられていません"

msgid "Can not add access to a public flavor."
msgstr "パブリックフレーバーにアクセスを追加できません"

msgid "Can not find requested image"
msgstr "要求されたイメージが見つかりません"

#, python-format
msgid "Can not handle authentication request for %d credentials"
msgstr "%d 認証情報に関する認証要求を処理できません"

msgid "Can't retrieve root device path from instance libvirt configuration"
msgstr "インスタンスの libvirt 設定からルートデバイスのパスを取得できません"

#, python-format
msgid ""
"Cannot '%(action)s' instance %(server_id)s while it is in %(attr)s %(state)s"
msgstr ""
"インスタンス %(server_id)s が %(attr)s %(state)s にある間は '%(action)s' を行"
"うことはできません"

#, python-format
msgid ""
"Cannot access \"%(instances_path)s\", make sure the path exists and that you "
"have the proper permissions. In particular Nova-Compute must not be executed "
"with the builtin SYSTEM account or other accounts unable to authenticate on "
"a remote host."
msgstr ""
"\"%(instances_path)s\" にアクセスできません。パスが存在し、適切な許可を持って"
"いることを確認してください。特に、Nova-Compute は、リモートホスト上で認証でき"
"ない組み込みのシステムアカウント等のアカウントで実行してはなりません。"

#, python-format
msgid "Cannot add host to aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""
"ホストをアグリゲート %(aggregate_id)s に追加できません。理由: %(reason)s。"

msgid "Cannot attach one or more volumes to multiple instances"
msgstr "1 つのボリュームを複数のインスタンスに接続できません"

#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr ""
"親のない %(objtype)s オブジェクトで %(method)s を呼び出すことはできません"

#, python-format
msgid ""
"Cannot determine the parent storage pool for %s; cannot determine where to "
"store images"
msgstr ""
"%s の親のストレージプールを検出できません。イメージを保存する場所を決定できま"
"せん。"

msgid "Cannot find image for rebuild"
msgstr "再作成用のイメージが見つかりません"

#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s"
msgstr "ホスト %(host)s をアグリゲート %(id)s から削除できません"

#, python-format
msgid "Cannot remove host from aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""
"ホストをアグリゲート %(aggregate_id)s から削除できません。理由: %(reason)s。"

msgid "Cannot rescue a volume-backed instance"
msgstr "ボリュームを使ったインスタンスはレスキューできません"

#, python-format
msgid ""
"Cannot resize the root disk to a smaller size. Current size: "
"%(curr_root_gb)s GB. Requested size: %(new_root_gb)s GB."
msgstr ""
"ルートディスクのサイズを小さくすることはできません。現在のサイズ: "
"%(curr_root_gb)s GB。要求されたサイズ: %(new_root_gb)s GB。"

msgid ""
"Cannot set cpu thread pinning policy in a non dedicated cpu pinning policy"
msgstr ""
"専用でない CPU の固定ポリシーではCPU スレッドの固定ポリシーを設定できません"

msgid "Cannot set realtime policy in a non dedicated cpu pinning policy"
msgstr ""
"専用でない CPU の固定ポリシーではリアルタイムのポリシーを設定できません"

#, python-format
msgid "Cannot update aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr "アグリゲート %(aggregate_id)s を更新できません。理由: %(reason)s。"

#, python-format
msgid ""
"Cannot update metadata of aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""
"アグリゲート %(aggregate_id)s のメタデータを更新できません。理由: "
"%(reason)s。"

#, python-format
msgid "Cell %(uuid)s has no mapping."
msgstr "セル %(uuid)s にはマッピングがありません。"

#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: %(unders)s"
msgstr "変更によって、リソース %(unders)s の使用量が 0 未満になります"

#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr "クラス %(class_name)s が見つかりませんでした: %(exception)s"

#, python-format
msgid ""
"Command Not supported. Please use Ironic command %(cmd)s to perform this "
"action."
msgstr ""
"コマンドはサポートされていません。このアクションを実行するには、Ironic コマン"
"ド %(cmd)s を使用してください。"

#, python-format
msgid "Compute host %(host)s could not be found."
msgstr "コンピュートホスト %(host)s が見つかりませんでした。"

#, python-format
msgid "Compute host %s not found."
msgstr "コンピュートホスト %s が見つかりません。"

#, python-format
msgid "Compute service of %(host)s is still in use."
msgstr "%(host)s のコンピュートサービスが依然として使用されています。"

#, python-format
msgid "Compute service of %(host)s is unavailable at this time."
msgstr "この時点では %(host)s のコンピュートサービスを使用できません。"

#, python-format
msgid "Config drive format '%(format)s' is not supported."
msgstr "コンフィグドライブ形式 %(format)s がサポートされません。"

#, python-format
msgid ""
"Config requested an explicit CPU model, but the current libvirt hypervisor "
"'%s' does not support selecting CPU models"
msgstr ""
"設定で、明示的な CPU モデルが要求されましたが、現在の libvirt ハイパーバイ"
"ザー '%s' は CPU モデルの選択をサポートしていません"

#, python-format
msgid ""
"Conflict updating instance %(instance_uuid)s, but we were unable to "
"determine the cause"
msgstr ""
"インスタンス %(instance_uuid)s の更新で競合が発生したものの、原因を特定できま"
"せんでした。"

#, python-format
msgid ""
"Conflict updating instance %(instance_uuid)s. Expected: %(expected)s. "
"Actual: %(actual)s"
msgstr ""
"インスタンス %(instance_uuid)s の更新で競合が発生しました。%(expected)s を期"
"待したものの、実際には %(actual)s が得られました"

#, python-format
msgid "Connection to cinder host failed: %(reason)s"
msgstr "cinder ホストへの接続に失敗しました: %(reason)s"

#, python-format
msgid "Connection to glance host %(server)s failed: %(reason)s"
msgstr "glance ホスト %(server)s への接続に失敗しました: %(reason)s"

#, python-format
msgid "Connection to libvirt lost: %s"
msgstr "libvirt との接続が失われました: %s"

#, python-format
msgid ""
"Console log output could not be retrieved for instance %(instance_id)s. "
"Reason: %(reason)s"
msgstr ""
"インスタンス %(instance_id)s についてコンソールログの出力を取得できませんでし"
"た。理由: %(reason)s"

msgid "Constraint not met."
msgstr "制約が満たされていません。"

#, python-format
msgid "Converted to raw, but format is now %s"
msgstr "raw 形式に変換されましたが、現在の形式は %s です"

#, fuzzy, python-format
msgid "Could not attach image to loopback: %s"
msgstr "イメージをループバック %s にアタッチできません。"

#, python-format
msgid "Could not fetch image %(image_id)s"
msgstr "イメージ %(image_id)s を取り出すことができませんでした"

#, python-format
msgid "Could not find a handler for %(driver_type)s volume."
msgstr "%(driver_type)s ボリュームのハンドラーが見つかりませんでした。"

#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr "ホスト %(host)s 上でバイナリー %(binary)s が見つかりませんでした。"

#, python-format
msgid "Could not find config at %(path)s"
msgstr "%(path)s に config が見つかりませんでした"

msgid "Could not find the datastore reference(s) which the VM uses."
msgstr "VM が使用するデータストア参照が見つかりませんでした。"

#, python-format
msgid "Could not load line %(line)s, got error %(error)s"
msgstr ""
"行 %(line)s をロードできませんでした。エラー %(error)s を受け取りました"

#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr ""
"paste アプリケーション '%(name)s' を %(path)s からロードできませんでした"

#, python-format
msgid ""
"Could not mount vfat config drive. %(operation)s failed. Error: %(error)s"
msgstr ""
"vfat コンフィグドライブをマウントできません。%(operation)s が失敗しました。エ"
"ラー: %(error)s"

#, python-format
msgid "Could not upload image %(image_id)s"
msgstr "イメージ %(image_id)s をアップロードできませんでした"

msgid "Creation of virtual interface with unique mac address failed"
msgstr "一意な MAC アドレスを持つ仮想インターフェースを作成できませんでした"

#, python-format
msgid "Datastore regex %s did not match any datastores"
msgstr "データストア regex %s がどのデータストアとも一致しませんでした"

msgid "Datetime is in invalid format"
msgstr "日時が無効な形式です"

msgid "Default PBM policy is required if PBM is enabled."
msgstr "PBM が有効になっている場合、デフォルト PBM ポリシーは必須です。"

#, python-format
msgid "Device '%(device)s' not found."
msgstr "デバイス '%(device)s' が見つかりません。"

msgid "Device name contains spaces."
msgstr "デバイス名に空白が含まれています。"

msgid "Device name empty or too long."
msgstr "デバイス名が空か、長すぎます。"

#, python-format
msgid "Device type mismatch for alias '%s'"
msgstr "別名 '%s' のデバイスタイプが一致しません"

#, python-format
msgid "Disk format %(disk_format)s is not acceptable"
msgstr "ディスク形式 %(disk_format)s は受け付けられません"

#, python-format
msgid "Disk info file is invalid: %(reason)s"
msgstr "ディスク情報ファイルが無効です: %(reason)s"

#, python-format
msgid "Driver Error: %s"
msgstr "ドライバーエラー: %s"

#, python-format
msgid "Error attempting to run %(method)s"
msgstr "%(method)s を実行しようとしてエラーが発生しました"

#, python-format
msgid ""
"Error destroying the instance on node %(node)s. Provision state still "
"'%(state)s'."
msgstr ""
"インスタンスをノード %(node)s で破棄しているときにエラーが発生しました。プロ"
"ビジョニング状態は '%(state)s' です。"

#, python-format
msgid "Error during unshelve instance %(instance_id)s: %(reason)s"
msgstr "インスタンス %(instance_id)s の復元中のエラー: %(reason)s"

#, python-format
msgid ""
"Error from libvirt while getting domain info for %(instance_name)s: [Error "
"Code %(error_code)s] %(ex)s"
msgstr ""
"%(instance_name)s のドメイン情報を取得している際に、libvirt でエラーが発生し"
"ました: [エラーコード %(error_code)s] %(ex)s"

#, python-format
msgid ""
"Error from libvirt while looking up %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""
"%(instance_name)s の検索中に libvirt でエラーが発生しました: [エラーコード "
"%(error_code)s] %(ex)s"

#, python-format
msgid ""
"Error from libvirt while quiescing %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""
"%(instance_name)s の正常終了中に libvirt でエラーが発生しました: [エラーコー"
"ド %(error_code)s] %(ex)s"

#, python-format
msgid ""
"Error from libvirt while set password for username \"%(user)s\": [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""
"ユーザー名 \"%(user)s\" のパスワードの設定中に libvirt でエラーが発生しまし"
"た: [エラーコード %(error_code)s] %(ex)s"

#, python-format
msgid ""
"Error mounting %(device)s to %(dir)s in image %(image)s with libguestfs "
"(%(e)s)"
msgstr ""
"libguestfs (%(e)s) を使用してイメージ %(image)s の %(dir)s に %(device)s をマ"
"ウントする際にエラーが発生しました"

#, python-format
msgid "Error mounting %(image)s with libguestfs (%(e)s)"
msgstr ""
"libguestfs (%(e)s) を使用してイメージ %(image)s をマウントする際にエラーが発"
"生しました"

#, python-format
msgid "Error when creating resource monitor: %(monitor)s"
msgstr "リソースモニター %(monitor)s を作成するときにエラーが発生しました"

#, python-format
msgid "Event %(event)s not found for action id %(action_id)s"
msgstr ""
"アクション ID %(action_id)s に対応するイベント %(event)s が見つかりません"

msgid "Event must be an instance of nova.virt.event.Event"
msgstr "イベントは nova.virt.event.Event のインスタンスでなければなりません"

#, python-format
msgid ""
"Exceeded max scheduling attempts %(max_attempts)d for instance "
"%(instance_uuid)s. Last exception: %(exc_reason)s"
msgstr ""
"インスタンス %(instance_uuid)s に関してスケジューリング可能な最大試行回数 "
"%(max_attempts)d を超えました。直近の例外: %(exc_reason)s"

#, python-format
msgid ""
"Exceeded max scheduling retries %(max_retries)d for instance "
"%(instance_uuid)s during live migration"
msgstr ""
"ライブマイグレーション時にインスタンス %(instance_uuid)s の最大スケジューリン"
"グ再試行回数 %(max_retries)d を超えました"

#, python-format
msgid "Exceeded maximum number of retries. %(reason)s"
msgstr "再試行の最大回数を超えました。%(reason)s"

#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr "UUID が必要ですが、%(uuid)s を受け取りました。"

msgid "Extracting vmdk from OVA failed."
msgstr "OVA からの vmdk の取得に失敗しました。"

#, python-format
msgid "Failed to access port %(port_id)s: %(reason)s"
msgstr "ポート %(port_id)s へのアクセスに失敗しました: %(reason)s"

#, python-format
msgid "Failed to allocate the network(s) with error %s, not rescheduling."
msgstr ""
"エラー %s が発生したため、ネットワークを割り当てることができませんでした。再"
"スケジュールは行われません。"

msgid "Failed to allocate the network(s), not rescheduling."
msgstr ""
"ネットワークを割り当てることができませんでした。再スケジュールは行われませ"
"ん。"

#, python-format
msgid "Failed to attach network adapter device to %(instance_uuid)s"
msgstr ""
"ネットワークアダプターデバイスを %(instance_uuid)s に接続できませんでした"

#, python-format
msgid "Failed to deploy instance: %(reason)s"
msgstr "インスタンスをデプロイできませんでした: %(reason)s"

#, python-format
msgid "Failed to detach PCI device %(dev)s: %(reason)s"
msgstr "PCI デバイス %(dev)s を切り離すことができませんでした: %(reason)s"

#, python-format
msgid "Failed to detach network adapter device from %(instance_uuid)s"
msgstr ""
"ネットワークアダプターデバイスを %(instance_uuid)s から切り離すことができませ"
"んでした"

#, python-format
msgid "Failed to encrypt text: %(reason)s"
msgstr "テキストの暗号化に失敗しました: %(reason)s"

#, python-format
msgid "Failed to launch instances: %(reason)s"
msgstr "インスタンスを起動できませんでした: %(reason)s"

#, python-format
msgid "Failed to map partitions: %s"
msgstr "パーティションのマッピングに失敗しました: %s"

#, python-format
msgid "Failed to mount filesystem: %s"
msgstr "ファイルシステム %s のマウントに失敗しました。"

#, python-format
msgid "Failed to power off instance: %(reason)s"
msgstr "インスタンスの電源オフに失敗しました: %(reason)s"

#, python-format
msgid "Failed to power on instance: %(reason)s"
msgstr "インスタンスの電源オンに失敗しました: %(reason)s"

#, python-format
msgid "Failed to provision instance %(inst)s: %(reason)s"
msgstr "インスタンス %(inst)s をプロビジョニングできませんでした: %(reason)s"

#, python-format
msgid "Failed to read or write disk info file: %(reason)s"
msgstr "ディスク情報ファイルの読み取りまたは書き込みに失敗しました: %(reason)s"

#, python-format
msgid "Failed to reboot instance: %(reason)s"
msgstr "インスタンスをリブートできませんでした: %(reason)s"

#, python-format
msgid "Failed to remove volume(s): (%(reason)s)"
msgstr "ボリュームの削除に失敗しました: (%(reason)s)"

#, python-format
msgid "Failed to request Ironic to rebuild instance %(inst)s: %(reason)s"
msgstr ""
"インスタンス %(inst)s の再構築を Ironic に要求できませんでした: %(reason)s"

#, python-format
msgid "Failed to resume instance: %(reason)s"
msgstr "インスタンスの再開に失敗しました: %(reason)s"

#, python-format
msgid "Failed to run qemu-img info on %(path)s : %(error)s"
msgstr "qemu-img info を %(path)s に対して実行できませんでした: %(error)s"

#, python-format
msgid "Failed to set admin password on %(instance)s because %(reason)s"
msgstr "%(instance)s で管理者パスワードの設定に失敗しました。理由: %(reason)s"

#, python-format
msgid "Failed to suspend instance: %(reason)s"
msgstr "インスタンスを休止できませんでした: %(reason)s"

#, python-format
msgid "Failed to terminate instance: %(reason)s"
msgstr "インスタンスを削除できませんでした: %(reason)s"

msgid "Failure prepping block device."
msgstr "ブロックデバイスを準備できませんでした"

#, python-format
msgid "File %(file_path)s could not be found."
msgstr "ファイル %(file_path)s が見つかりませんでした。"

#, python-format
msgid "Fixed IP %(ip)s is not a valid ip address for network %(network_id)s."
msgstr ""
"Fixed IP %(ip)s はネットワーク %(network_id)s の有効な IP アドレスではありま"
"せん。"

#, python-format
msgid "Fixed IP %s is already in use."
msgstr "Fixed IP %s は既に使用中です。"

#, python-format
msgid ""
"Fixed IP address %(address)s is already in use on instance %(instance_uuid)s."
msgstr ""
"Fixed IP アドレス %(address)s はインスタンス %(instance_uuid)s で既に使用され"
"ています。"

#, python-format
msgid "Fixed IP not found for address %(address)s."
msgstr " アドレス %(address)s に対応する Fixed IP が見つかりません。"

#, python-format
msgid "Flavor %(flavor_id)s could not be found."
msgstr "フレーバー %(flavor_id)s が見つかりませんでした。"

#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(extra_specs_key)s."
msgstr ""
"フレーバー %(flavor_id)s にはキー %(extra_specs_key)s を持つ追加スペックはあ"
"りません。"

#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(key)s."
msgstr ""
"フレーバー %(flavor_id)s にはキー %(key)s を持つ追加スペックはありません。"

#, python-format
msgid ""
"Flavor %(id)s extra spec cannot be updated or created after %(retries)d "
"retries."
msgstr ""
"%(retries)d 回の再試行の後では、フレーバー %(id)s の追加仕様の更新と作成を行"
"うことはできません。"

#, python-format
msgid ""
"Flavor access already exists for flavor %(flavor_id)s and project "
"%(project_id)s combination."
msgstr ""
"フレーバー %(flavor_id)s とプロジェクト %(project_id)s の組み合わせに対応する"
"フレーバーアクセスは既に存在します。"

#, python-format
msgid "Flavor access not found for %(flavor_id)s / %(project_id)s combination."
msgstr ""
"%(flavor_id)s / %(project_id)s の組み合わせに対応するフレーバーアクセスが見つ"
"かりません。"

msgid "Flavor used by the instance could not be found."
msgstr "インスタンスで使用されたフレーバーが見つかりませんでした"

#, python-format
msgid "Flavor with ID %(flavor_id)s already exists."
msgstr "ID %(flavor_id)s を持つフレーバーは既に存在します。"

#, python-format
msgid "Flavor with name %(flavor_name)s could not be found."
msgstr "名前が %(flavor_name)s のフレーバーが見つかりませんでした。"

#, python-format
msgid "Flavor with name %(name)s already exists."
msgstr "名前が %(name)s のフレーバーは既に存在します。"

#, python-format
msgid ""
"Flavor's disk is smaller than the minimum size specified in image metadata. "
"Flavor disk is %(flavor_size)i bytes, minimum size is %(image_min_disk)i "
"bytes."
msgstr ""
"フレーバーのディスクサイズがイメージのメタデータで指定された最小サイズよりも"
"小さくなっています。フレーバーディスクは %(flavor_size)i バイト、最小サイズ"
"は %(image_min_disk)i バイトです。"

#, python-format
msgid ""
"Flavor's disk is too small for requested image. Flavor disk is "
"%(flavor_size)i bytes, image is %(image_size)i bytes."
msgstr ""
"フレーバーのディスクサイズがリクエストされたイメージに対し小さすぎます。フ"
"レーバーディスクは %(flavor_size)i バイト、イメージは %(image_size)i バイトで"
"す。"

msgid "Flavor's memory is too small for requested image."
msgstr "フレーバーのメモリーは要求されたイメージに対して小さすぎます。"

#, python-format
msgid "Floating IP %(address)s association has failed."
msgstr "Floating IP %(address)s の割り当てに失敗しました。"

#, python-format
msgid "Floating IP %(address)s is associated."
msgstr "Floating IP %(address)s が割り当てられています。"

#, python-format
msgid "Floating IP %(address)s is not associated with instance %(id)s."
msgstr ""
"Floating IP %(address)s はインスタンス %(id)s に割り当てられていません。"

#, python-format
msgid "Floating IP not found for ID %(id)s."
msgstr "ID %(id)s の Floating IP が見つかりません。"

#, python-format
msgid "Floating IP not found for ID %s"
msgstr "ID %s の Floating IP が見つかりません"

#, python-format
msgid "Floating IP not found for address %(address)s."
msgstr "アドレス %(address)s に対応する Floating IP が見つかりません。"

msgid "Floating IP pool not found."
msgstr "Floating IP プールが見つかりません。"

msgid ""
"Forbidden to exceed flavor value of number of serial ports passed in image "
"meta."
msgstr ""
"イメージメタデータで渡されるシリアルポート数のフレーバー値を超えないようにし"
"てください。"

msgid "Found no disk to snapshot."
msgstr "スナップショットの作成対象のディスクが見つかりません"

msgid "Guest does not have a console available."
msgstr "ゲストはコンソールを使用することはできません。"

#, python-format
msgid "Host %(host)s could not be found."
msgstr "ホスト %(host)s が見つかりませんでした。"

#, python-format
msgid "Host %(host)s is already mapped to cell %(uuid)s"
msgstr "ホスト %(host)s が既にセル %(uuid)s にマッピングされています"

#, python-format
msgid "Host '%(name)s' is not mapped to any cell"
msgstr "ホスト '%(name)s' がどのセルにもマッピングされません"

msgid "Host PowerOn is not supported by the Hyper-V driver"
msgstr "ホスト電源オンは Hyper-V ドライバーではサポートされていません"

msgid "Host aggregate is not empty"
msgstr "ホストアグリゲートが空ではありません"

msgid "Host does not support guests with NUMA topology set"
msgstr "ホストが NUMA トポロジーが設定されたゲストをサポートしていません"

msgid "Host does not support guests with custom memory page sizes"
msgstr ""
"ホストがカスタムのメモリーページサイズが指定されたゲストをサポートしていませ"
"ん"

msgid "Hypervisor driver does not support post_live_migration_at_source method"
msgstr ""
"ハイパーバイザードライバーが post_live_migration_at_source メソッドをサポート"
"していません"

#, python-format
msgid "Hypervisor virt type '%s' is not valid"
msgstr "ハイバーバイザーの仮想化タイプ '%s' が有効ではありません"

#, python-format
msgid "Hypervisor virtualization type '%(hv_type)s' is not recognised"
msgstr "ハイパーバイザー仮想化タイプ '%(hv_type)s' は認識されていません"

#, python-format
msgid "Hypervisor with ID '%s' could not be found."
msgstr "ID '%s' のハイパーバイザーが見つかりませんでした。"

#, python-format
msgid "IP allocation over quota in pool %s."
msgstr "IP の割り当て量がプール %s 内のクォータを超えています。"

msgid "IP allocation over quota."
msgstr "IP の割り当て量がクォータを超えています。"

#, python-format
msgid "Image %(image_id)s could not be found."
msgstr "イメージ %(image_id)s が見つかりませんでした。"

#, python-format
msgid "Image %(image_id)s is not active."
msgstr "イメージ %(image_id)s はアクティブではありません。"

#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr "イメージ %(image_id)s は受け付けられません: %(reason)s"

msgid "Image disk size greater than requested disk size"
msgstr "イメージディスクが、要求されたディスクサイズよりも大きなサイズです"

msgid "Image is not raw format"
msgstr "イメージは raw 形式ではありません"

msgid "Image metadata limit exceeded"
msgstr "イメージメタデータ数の上限を超えました"

#, python-format
msgid "Image model '%(image)s' is not supported"
msgstr "イメージモデル '%(image)s' はサポートされません"

msgid "Image not found."
msgstr "イメージが見つかりません。"

#, python-format
msgid ""
"Image property '%(name)s' is not permitted to override NUMA configuration "
"set against the flavor"
msgstr ""
"イメージプロパティー '%(name)s' で、フレーバーに対して設定された NUMA 構成を"
"オーバーライドすることは許可されません"

msgid ""
"Image property 'hw_cpu_policy' is not permitted to override CPU pinning "
"policy set against the flavor"
msgstr ""
"イメージプロパティー 'hw_cpu_policy' はこのフレーバーでは設定されたCPU コア固"
"定ポリシーのオーバーライドを許可されていません"

msgid ""
"Image property 'hw_cpu_thread_policy' is not permitted to override CPU "
"thread pinning policy set against the flavor"
msgstr ""
"イメージプロパティー 'hw_cpu_thread_policy' は、フレーバーに設定された CPU ス"
"レッドの固定ポリシーを上書きすることはできません。"

msgid "Image that the instance was started with could not be found."
msgstr "インスタンスの起動時に使用されたイメージが見つかりませんでした。"

#, python-format
msgid "Image's config drive option '%(config_drive)s' is invalid"
msgstr "イメージのコンフィグドライブのオプション '%(config_drive)s' は無効です"

msgid ""
"Images with destination_type 'volume' need to have a non-zero size specified"
msgstr ""
"destination_type 'volume' を含むイメージには、ゼロ以外のサイズが指定されてい"
"る必要があります"

msgid "In ERROR state"
msgstr "エラー状態です"

#, python-format
msgid "In states %(vm_state)s/%(task_state)s, not RESIZED/None"
msgstr "状態は %(vm_state)s/%(task_state)s です。RESIZED/None ではありません"

#, python-format
msgid "In-progress live migration %(id)s is not found for server %(uuid)s."
msgstr ""
"サーバー %(uuid)s で進行中のライブマイグレーション %(id)s が見つかりません。"

msgid ""
"Incompatible settings: ephemeral storage encryption is supported only for "
"LVM images."
msgstr ""
"設定に互換性がありません:  一時ストレージ暗号化は LVM イメージでのみサポート"
"されています。"

#, python-format
msgid "Info cache for instance %(instance_uuid)s could not be found."
msgstr ""
"インスタンス %(instance_uuid)s 用の情報キャッシュが見つかりませんでした。"

#, python-format
msgid ""
"Instance %(instance)s and volume %(vol)s are not in the same "
"availability_zone. Instance is in %(ins_zone)s. Volume is in %(vol_zone)s"
msgstr ""
"インスタンス %(instance)s とボリューム %(vol)s は同じアベイラビリティーゾーン"
"にありません。インスタンスは %(ins_zone)s に、ボリュームは %(vol_zone)s にあ"
"ります"

#, python-format
msgid "Instance %(instance)s does not have a port with id %(port)s"
msgstr "インスタンス %(instance)s に ID %(port)s のポートがありません"

#, python-format
msgid "Instance %(instance_id)s cannot be rescued: %(reason)s"
msgstr "インスタンス %(instance_id)s をレスキューできません: %(reason)s"

#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr "インスタンス %(instance_id)s が見つかりませんでした。"

#, python-format
msgid "Instance %(instance_id)s has no tag '%(tag)s'"
msgstr "インスタンス %(instance_id)s にタグ \"%(tag)s\" がありません"

#, python-format
msgid "Instance %(instance_id)s is not in rescue mode"
msgstr "インスタンス %(instance_id)s はレスキューモードではありません。"

#, python-format
msgid "Instance %(instance_id)s is not ready"
msgstr "インスタンス %(instance_id)s の準備ができていません"

#, python-format
msgid "Instance %(instance_id)s is not running."
msgstr "インスタンス %(instance_id)s は実行されていません。"

#, python-format
msgid "Instance %(instance_id)s is unacceptable: %(reason)s"
msgstr "インスタンス %(instance_id)s は受け付けられません: %(reason)s"

#, python-format
msgid "Instance %(instance_uuid)s does not specify a NUMA topology"
msgstr "インスタンス %(instance_uuid)s で NUMA トポロジーが指定されていません"

#, python-format
msgid "Instance %(instance_uuid)s does not specify a migration context."
msgstr ""
"インスタンス %(instance_uuid)s がマイグレーションのコンテキストを設定していま"
"せん。"

#, python-format
msgid ""
"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot %(method)s while "
"the instance is in this state."
msgstr ""
"インスタンス %(instance_uuid)s は %(attr)s %(state)s 状態です。インスタンスが"
"この状態にある間は %(method)s を行えません。"

#, python-format
msgid "Instance %(instance_uuid)s is locked"
msgstr "インスタンス %(instance_uuid)s はロックされています"

#, python-format
msgid ""
"Instance %(instance_uuid)s requires config drive, but it does not exist."
msgstr ""
"インスタンス %(instance_uuid)s にはコンフィグドライブが必要ですが、存在しませ"
"ん。"

#, python-format
msgid "Instance %(name)s already exists."
msgstr "インスタンス %(name)s は既に存在します。"

#, python-format
msgid "Instance %(server_id)s is in an invalid state for '%(action)s'"
msgstr ""
"インスタンス %(server_id)s は '%(action)s' が実行できない状態にあります"

#, python-format
msgid "Instance %(uuid)s has no mapping to a cell."
msgstr "インスタンス %(uuid)s にはセルに対するマッピングがありません。"

#, python-format
msgid "Instance %s not found"
msgstr "インスタンス %s が見つかりません"

#, python-format
msgid "Instance %s provisioning was aborted"
msgstr "インスタンス %s のプロビジョニングが中止しました。"

msgid "Instance could not be found"
msgstr "インスタンスが見つかりませんでした"

msgid "Instance disk to be encrypted but no context provided"
msgstr ""
"インスタンスディスクの暗号化が必要ですが、コンテキストが指定されていません。"

msgid "Instance event failed"
msgstr "インスタンスイベントが失敗しました"

#, python-format
msgid "Instance group %(group_uuid)s already exists."
msgstr "インスタンスグループ %(group_uuid)s は既に存在します。"

#, python-format
msgid "Instance group %(group_uuid)s could not be found."
msgstr "インスタンスグループ %(group_uuid)s が見つかりませんでした。"

#, fuzzy
msgid "Instance has no source host"
msgstr "インスタンスにソースホストがありません"

msgid "Instance has not been resized."
msgstr "インスタンスのサイズ変更が行われていません"

#, python-format
msgid "Instance hostname %(hostname)s is not a valid DNS name"
msgstr "インスタンスのホスト名 %(hostname)s は有効な DNS 名ではありません。"

msgid "Instance is not a member of specified network"
msgstr "インスタンスは指定されたネットワークのメンバーではありません"

#, python-format
msgid "Instance rollback performed due to: %s"
msgstr "インスタンスのロールバックが実行されました。原因: %s"

#, python-format
msgid ""
"Insufficient Space on Volume Group %(vg)s. Only %(free_space)db available, "
"but %(size)d bytes required by volume %(lv)s."
msgstr ""
"ボリュームグループ %(vg)s に十分なスペースがありません。使用可能なのは "
"%(free_space)db のみですが、ボリューム %(lv)s には %(size)d バイト必要です。"

#, python-format
msgid "Insufficient compute resources: %(reason)s."
msgstr "コンピュートリソースが不十分です: %(reason)s。"

#, python-format
msgid "Interface %(interface)s not found."
msgstr "インターフェース %(interface)s が見つかりません。"

#, python-format
msgid "Invalid Base 64 data for file %(path)s"
msgstr "ファイル %(path)s の Base64 データが無効です"

msgid "Invalid Connection Info"
msgstr "無効な接続情報"

#, python-format
msgid "Invalid ID received %(id)s."
msgstr "無効な ID %(id)s を受信しました。"

#, python-format
msgid "Invalid IP format %s"
msgstr "%s は無効な IP 形式です"

#, python-format
msgid "Invalid IP protocol %(protocol)s."
msgstr "無効な IP プロトコル %(protocol)s。"

msgid ""
"Invalid PCI Whitelist: The PCI whitelist can specify devname or address, but "
"not both"
msgstr ""
"無効な PCI ホワイトリスト: PCI ホワイトリストでは devname またはアドレスを指"
"定できますが、両方を指定することはできません"

#, python-format
msgid "Invalid PCI alias definition: %(reason)s"
msgstr "PCI エイリアス定義が無効です: %(reason)s"

#, python-format
msgid "Invalid Regular Expression %s"
msgstr "正規表現 %s は無効です"

#, python-format
msgid "Invalid characters in hostname '%(hostname)s'"
msgstr "ホスト名 '%(hostname)s' に無効な文字があります"

msgid "Invalid config_drive provided."
msgstr "無効な config_drive が指定されました。"

#, python-format
msgid "Invalid config_drive_format \"%s\""
msgstr "無効な config_drive_format \"%s\""

#, python-format
msgid "Invalid console type %(console_type)s"
msgstr "無効なコンソールタイプ %(console_type)s"

#, python-format
msgid "Invalid content type %(content_type)s."
msgstr "無効なコンテンツ形式 %(content_type)s。"

#, python-format
msgid "Invalid datetime string: %(reason)s"
msgstr "日時の文字列が無効です: %(reason)s"

msgid "Invalid device UUID."
msgstr "デバイス UUID が無効です。"

#, python-format
msgid "Invalid entry: '%s'"
msgstr "項目 '%s' は無効です"

#, python-format
msgid "Invalid entry: '%s'; Expecting dict"
msgstr "項目 '%s' は無効です。辞書型が期待されています"

#, python-format
msgid "Invalid entry: '%s'; Expecting list or dict"
msgstr "項目 '%s' は無効です。リストまたは辞書型が期待されています"

#, python-format
msgid "Invalid exclusion expression %r"
msgstr "排他式 %r は無効です"

#, python-format
msgid "Invalid image format '%(format)s'"
msgstr "イメージ形式 '%(format)s' は無効です"

#, python-format
msgid "Invalid image href %(image_href)s."
msgstr "無効なイメージ href %(image_href)s。"

#, python-format
msgid "Invalid inclusion expression %r"
msgstr "包含式 %r は無効です"

#, python-format
msgid ""
"Invalid input for field/attribute %(path)s. Value: %(value)s. %(message)s"
msgstr "フィールド/属性 %(path)s の入力が無効です。値: %(value)s。%(message)s"

#, python-format
msgid "Invalid input received: %(reason)s"
msgstr "無効な入力を受信しました: %(reason)s"

msgid "Invalid instance image."
msgstr "インスタンスイメージが無効です。"

#, python-format
msgid "Invalid is_public filter [%s]"
msgstr "無効な is_public フィルター [%s]"

msgid "Invalid key_name provided."
msgstr "無効な key_name が指定されました。"

#, python-format
msgid "Invalid memory page size '%(pagesize)s'"
msgstr "メモリーページサイズ \"%(pagesize)s\" が無効です"

msgid "Invalid metadata key"
msgstr "無効なメタデータキーです"

#, python-format
msgid "Invalid metadata size: %(reason)s"
msgstr "無効なメタデータサイズ: %(reason)s"

#, python-format
msgid "Invalid metadata: %(reason)s"
msgstr "メタデータが無効です: %(reason)s"

#, python-format
msgid "Invalid minDisk filter [%s]"
msgstr "無効な minDisk フィルター [%s]"

#, python-format
msgid "Invalid minRam filter [%s]"
msgstr "無効な minRam フィルター [%s]"

#, python-format
msgid "Invalid port range %(from_port)s:%(to_port)s. %(msg)s"
msgstr "無効なポート範囲 %(from_port)s:%(to_port)s。 %(msg)s"

msgid "Invalid proxy request signature."
msgstr "無効なプロキシー要求シグニチャー"

#, python-format
msgid "Invalid range expression %r"
msgstr "範囲式 %r は無効です"

msgid "Invalid service catalog json."
msgstr "無効なサービスカタログ JSON。"

msgid "Invalid start time. The start time cannot occur after the end time."
msgstr "無効な開始時刻。開始時刻を終了時刻より後にすることはできません。"

msgid "Invalid state of instance files on shared storage"
msgstr "共有ストレージ上のインスタンスファイルの無効な状態"

#, python-format
msgid "Invalid timestamp for date %s"
msgstr "日付 %s のタイムスタンプが無効です"

#, python-format
msgid "Invalid usage_type: %s"
msgstr "usage_type %s は無効です"

#, python-format
msgid "Invalid value for Config Drive option: %(option)s"
msgstr "コンフィグドライブのオプション %(option)s の値が無効です"

#, python-format
msgid "Invalid virtual interface address %s in request"
msgstr "リクエストに無効な仮想インターフェースアドレス %s があります"

#, python-format
msgid "Invalid volume access mode: %(access_mode)s"
msgstr "ボリュームアクセスモードが無効です: %(access_mode)s"

#, python-format
msgid "Invalid volume: %(reason)s"
msgstr "無効なボリューム: %(reason)s"

msgid "Invalid volume_size."
msgstr "volume_size が無効です。"

#, python-format
msgid "Ironic node uuid not supplied to driver for instance %s."
msgstr ""
"Ironic ノード uuid が、インスタンス %s のドライバーに提供されていません。"

#, python-format
msgid ""
"It is not allowed to create an interface on external network %(network_uuid)s"
msgstr ""
"外部ネットワーク %(network_uuid)s でインターフェースを作成することは許可され"
"ていません"

msgid ""
"Key Names can only contain alphanumeric characters, periods, dashes, "
"underscores, colons and spaces."
msgstr ""
"キー名に使用できるのは、英数字、ピリオド、ダッシュ、アンダースコアー、コロ"
"ン、および空白のみです。"

#, python-format
msgid "Key manager error: %(reason)s"
msgstr "鍵マネージャーエラー: %(reason)s"

#, python-format
msgid "Key pair '%(key_name)s' already exists."
msgstr "キーペア '%(key_name)s' は既に存在します。"

#, python-format
msgid "Keypair %(name)s not found for user %(user_id)s"
msgstr "ユーザー %(user_id)s のキーペア %(name)s が見つかりません"

#, python-format
msgid "Keypair data is invalid: %(reason)s"
msgstr "キーペアデータが無効です: %(reason)s"

msgid "Limits only supported from vCenter 6.0 and above"
msgstr "上限が適用されるのは、vCenter 6.0 以降の場合のみです。"

#, python-format
msgid "Live migration %(id)s for server %(uuid)s is not in progress."
msgstr "サーバー %(uuid)s のマイグレーション %(id)s は進行中ではありません。"

#, python-format
msgid "Malformed message body: %(reason)s"
msgstr "メッセージ本文の形式に誤りがあります: %(reason)s"

#, python-format
msgid ""
"Malformed request URL: URL's project_id '%(project_id)s' doesn't match "
"Context's project_id '%(context_project_id)s'"
msgstr ""
"誤った形式のリクエスト URL です。URL の project_id '%(project_id)s' がコンテ"
"キストの project_id '%(context_project_id)s' と一致しません"

msgid "Malformed request body"
msgstr "誤った形式のリクエスト本文"

msgid "Mapping image to local is not supported."
msgstr "ローカルへのイメージマッピングはサポートしていません。"

#, python-format
msgid "Marker %(marker)s could not be found."
msgstr "マーカー %(marker)s が見つかりませんでした。"

msgid "Maximum number of floating IPs exceeded"
msgstr "Floating IP の最大数を超えました"

#, python-format
msgid "Maximum number of metadata items exceeds %(allowed)d"
msgstr "メタデータ項目の最大数が %(allowed)d を超えています"

msgid "Maximum number of ports exceeded"
msgstr "最大ポート数を超えました"

msgid "Maximum number of security groups or rules exceeded"
msgstr "セキュリティーグループまたはルールの最大数を超えました"

msgid "Metadata item was not found"
msgstr "メタデータ項目が見つかりませんでした"

msgid "Metadata property key greater than 255 characters"
msgstr "メタデータプロパティーのキーが 255 文字を超えています"

msgid "Metadata property value greater than 255 characters"
msgstr "メタデータプロパティーの値が 255 文字を超えています"

msgid "Metadata type should be dict."
msgstr "メタデータタイプは dict でなければなりません。"

#, python-format
msgid ""
"Metric %(name)s could not be found on the compute host node %(host)s."
"%(node)s."
msgstr ""
"コンピュートホストノード %(host)s.%(node)s では、メトリック %(name)s は見つか"
"りませんでした。"

#, python-format
msgid "Migration %(id)s for server %(uuid)s is not live-migration."
msgstr ""
"サーバー %(uuid)s のマイグレーション %(id)s はライブマイグレーションではあり"
"ません。"

#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr "マイグレーション %(migration_id)s が見つかりませんでした。"

#, python-format
msgid "Migration %(migration_id)s not found for instance %(instance_id)s"
msgstr ""
"インスタンス %(instance_id)s でマイグレーション %(migration_id)s が見つかりま"
"せん"

#, python-format
msgid ""
"Migration %(migration_id)s state of instance %(instance_uuid)s is %(state)s. "
"Cannot %(method)s while the migration is in this state."
msgstr ""
"インスタンス %(instance_uuid)s のマイグレーション %(migration_id)s の状態が "
"%(state)s です。マイグレーションがこの状態にある場合、%(method)s を実行できま"
"せん。"

#, python-format
msgid "Migration error: %(reason)s"
msgstr "マイグレーションエラー: %(reason)s"

msgid "Migration is not supported for LVM backed instances"
msgstr ""
"マイグレーションは LVM 形式のイメージを使用するインスタンスではサポートされて"
"いません"

#, python-format
msgid ""
"Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""
"状態が %(status)s のインスタンス %(instance_id)s のマイグレーションが見つかり"
"ません。"

#, python-format
msgid "Migration pre-check error: %(reason)s"
msgstr "マイグレーション事前検査エラー: %(reason)s"

#, python-format
msgid "Migration select destinations error: %(reason)s"
msgstr "マイグレーション先の選択エラー: %(reason)s"

#, python-format
msgid "Missing arguments: %s"
msgstr "引数 %s がありません"

msgid "Missing device UUID."
msgstr "デバイス UUID がありません。"

msgid "Missing disabled reason field"
msgstr "「無効化の理由」フィールドがありません"

msgid "Missing forced_down field"
msgstr "forced_down フィールドがありません"

msgid "Missing imageRef attribute"
msgstr "imageRef 属性が指定されていません"

#, python-format
msgid "Missing keys: %s"
msgstr "キーがありません: %s"

#, python-format
msgid "Missing parameter %s"
msgstr "パラメーター %s が欠落しています"

msgid "Missing parameter dict"
msgstr "パラメーター dict が指定されていません"

#, python-format
msgid ""
"More than one instance is associated with fixed IP address '%(address)s'."
msgstr ""
"複数のインスタンスが Fixed IP アドレス '%(address)s' に割り当てられています。"

msgid ""
"More than one possible network found. Specify network ID(s) to select which "
"one(s) to connect to."
msgstr ""
"複数の使用可能なネットワークが見つかりました。接続先のネットワークを選択する"
"には、ネットワーク ID を指定してください。"

msgid "More than one swap drive requested."
msgstr "複数のスワップドライブが要求されました。"

#, python-format
msgid "Multi-boot operating system found in %s"
msgstr "%s 内にブート可能なオペレーティングシステムが複数見つかりました"

msgid "Multiple X-Instance-ID headers found within request."
msgstr "リクエストに複数の X-Instance-ID ヘッダーが検出されました。"

msgid "Multiple X-Tenant-ID headers found within request."
msgstr "リクエストに複数の X-Tenant-ID ヘッダーが検出されました。"

#, python-format
msgid "Multiple floating IP pools matches found for name '%s'"
msgstr "名前が '%s' の Floating IP プールが複数見つかりました"

#, python-format
msgid "Multiple floating IPs are found for address %(address)s."
msgstr "アドレス %(address)s に対して複数の Floating IP が見つかりました。"

msgid ""
"Multiple hosts may be managed by the VMWare vCenter driver; therefore we do "
"not return uptime for just one host."
msgstr ""
"複数のホストが VMWare vCenter ドライバーによって管理されている可能性がありま"
"す。このため ホスト単位の稼働時間は返しません。"

msgid "Multiple possible networks found, use a Network ID to be more specific."
msgstr ""
"使用可能なネットワークが複数見つかりました。ネットワーク ID を具体的に指定し"
"てください。"

#, python-format
msgid ""
"Multiple security groups found matching '%s'. Use an ID to be more specific."
msgstr ""
"'%s' に一致するセキュリティーグループが複数見つかりました。より具体的な ID を"
"使用してください。"

msgid "Must input network_id when request IP address"
msgstr "IP アドレスを要求するときは、network_id を入力する必要があります"

msgid "Must not input both network_id and port_id"
msgstr "network_id と port_id の両方を入力しないでください"

msgid ""
"Must specify host_ip, host_username and host_password to use vmwareapi."
"VMwareVCDriver"
msgstr ""
"vmwareapi.VMwareVCDriver を使用するためのホスト IP、ユーザー名、ホストパス"
"ワードを指定する必要があります"

msgid "Must supply a positive value for max_number"
msgstr "max_number には正の値を指定する必要があります"

msgid "Must supply a positive value for max_rows"
msgstr "max_rows には正の値を指定する必要があります"

#, python-format
msgid "Network %(network_id)s could not be found."
msgstr "ネットワーク %(network_id)s が見つかりませんでした。"

#, python-format
msgid ""
"Network %(network_uuid)s requires a subnet in order to boot instances on."
msgstr ""
"ネットワーク %(network_uuid)s でインスタンスをブートするには、サブネットが必"
"要です。"

#, python-format
msgid "Network could not be found for bridge %(bridge)s"
msgstr "ブリッジ %(bridge)s のネットワークが見つかりませんでした"

#, python-format
msgid "Network could not be found for instance %(instance_id)s."
msgstr "インスタンス %(instance_id)s のネットワークが見つかりませんでした。"

msgid "Network not found"
msgstr "ネットワークが見つかりません"

msgid ""
"Network requires port_security_enabled and subnet associated in order to "
"apply security groups."
msgstr ""
"セキュリティーグループを適用するには、ネットワークが port_security_enabled に"
"なっていて、サブネットが関連付けられている必要があります。"

msgid "New volume must be detached in order to swap."
msgstr "スワップを行うには、新規ボリュームを切断する必要があります。"

msgid "New volume must be the same size or larger."
msgstr "新規ボリュームは同じサイズか、それ以上でなければなりません。"

#, python-format
msgid "No Block Device Mapping with id %(id)s."
msgstr "ID %(id)s を持つブロックデバイスマッピングがありません。"

msgid "No Unique Match Found."
msgstr "1 つだけ一致するデータが見つかりません。"

msgid "No compute host specified"
msgstr "コンピュートホストが指定されていません"

#, python-format
msgid "No configuration information found for operating system %(os_name)s"
msgstr "オペレーティングシステム %(os_name)s に関する設定情報が見つかりません"

#, python-format
msgid "No device with MAC address %s exists on the VM"
msgstr "MAC アドレス %s を持つデバイスが VM にありません"

#, python-format
msgid "No device with interface-id %s exists on VM"
msgstr "interface-id %s を持つデバイスが VM にありません"

#, python-format
msgid "No disk at %(location)s"
msgstr "%(location)s にディスクがありません"

#, python-format
msgid "No fixed IP addresses available for network: %(net)s"
msgstr "ネットワーク %(net)s で使用可能な Fixed IP アドレスがありません。"

msgid "No fixed IPs associated to instance"
msgstr "Fixed IP がインスタンスに割り当てられていません"

msgid "No free nbd devices"
msgstr "空きの nbd デバイスがありません"

msgid "No host available on cluster"
msgstr "クラスター上に使用可能なホストがありません"

msgid "No hosts found to map to cell, exiting."
msgstr "セルにマッピングするホストが見つかりません。処理を終了します。"

#, python-format
msgid "No hypervisor matching '%s' could be found."
msgstr "'%s' と合致するハイパーバイザーが見つかりませんでした。"

msgid "No image locations are accessible"
msgstr "イメージの場所にアクセスできません"

#, python-format
msgid ""
"No live migration URI configured and no default available for \"%(virt_type)s"
"\" hypervisor virtualization type."
msgstr ""
"ライブマイグレーションの URI が設定されておらず、ハイパーバイザーの仮想化タイ"
"プの \"%(virt_type)s\" で使用可能なデフォルトが存在しません。"

msgid "No more floating IPs available."
msgstr "使用可能な Floating IP はこれ以上ありません。"

#, python-format
msgid "No more floating IPs in pool %s."
msgstr "プール %s 内に Floating IP はこれ以上ありません。"

#, python-format
msgid "No mount points found in %(root)s of %(image)s"
msgstr "%(image)s の %(root)s にマウントポイントが見つかりません"

#, python-format
msgid "No operating system found in %s"
msgstr "%s 内にオペレーティングシステムが見つかりません"

msgid "No root disk defined."
msgstr "ルートディスクが定義されていません。"

#, python-format
msgid ""
"No specific network was requested and none are available for project "
"'%(project_id)s'."
msgstr ""
"特定のネットワークが要求されず、プロジェクト '%(project_id)s' で利用可能な"
"ネットワークがありません。"

msgid "No valid host found for cold migrate"
msgstr "コールドマイグレーションに有効なホストが見つかりません"

msgid "No valid host found for resize"
msgstr "サイズ変更の対象として有効なホストが見つかりません"

#, python-format
msgid "No valid host was found. %(reason)s"
msgstr "有効なホストが見つかりませんでした。%(reason)s"

#, python-format
msgid "No volume Block Device Mapping at path: %(path)s"
msgstr "ボリュームのブロックデバイスマッピングがパス %(path)s にありません"

#, python-format
msgid "No volume Block Device Mapping with id %(volume_id)s."
msgstr ""
"ID %(volume_id)s を持つボリュームのブロックデバイスマッピングがありません。"

#, python-format
msgid "Node %s could not be found."
msgstr "ノード %s が見つかりませんでした。"

#, python-format
msgid "Not able to acquire a free port for %(host)s"
msgstr "%(host)s 用の未使用ポートを取得できません"

#, python-format
msgid "Not able to bind %(host)s:%(port)d, %(error)s"
msgstr "%(host)s:%(port)d をバインドできません。%(error)s"

#, python-format
msgid ""
"Not all Virtual Functions of PF %(compute_node_id)s:%(address)s are free."
msgstr ""
"PF %(compute_node_id)s の %(address)s のすべての Virtual Function に空きがあ"
"るとは限りません。"

msgid "Not an rbd snapshot"
msgstr "rbd スナップショットではありません"

#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr "イメージ %(image_id)s への権限がありません。"

msgid "Not authorized."
msgstr "権限がありません。"

msgid "Not enough parameters to build a valid rule."
msgstr "有効なルールを作成するだけの十分なパラメータがありません"

msgid "Not implemented on Windows"
msgstr "Windows では実装されていません"

msgid "Not stored in rbd"
msgstr "rbd 内に保管されていません"

msgid "Nothing was archived."
msgstr "アーカイブは行われませんでした"

#, python-format
msgid "Nova requires libvirt version %s or greater."
msgstr "Nova には libvirt バージョン %s 以降が必要です。"

msgid "Number of Rows Archived"
msgstr "アーカイブ済みの行数"

#, python-format
msgid "Object action %(action)s failed because: %(reason)s"
msgstr "オブジェクトのアクション %(action)s が失敗しました。原因: %(reason)s"

msgid "Old volume is attached to a different instance."
msgstr "旧ボリュームは別のインスタンスに接続されています。"

#, python-format
msgid "One or more hosts already in availability zone(s) %s"
msgstr "アベイラビリティーゾーン %s に 1 つ以上のホストが既にあります"

msgid "Only administrators may list deleted instances"
msgstr "削除済みインスタンスの一覧を取得できるのは管理者のみです。"

msgid "Origin header does not match this host."
msgstr "オリジンヘッダーがこのホストに一致しません。"

msgid "Origin header not valid."
msgstr "オリジンヘッダーが無効です。"

msgid "Origin header protocol does not match this host."
msgstr "オリジンヘッダープロトコルがこのホストに一致しません。"

#, python-format
msgid "PCI Device %(node_id)s:%(address)s not found."
msgstr "PCI デバイス %(node_id)s:%(address)s が見つかりません。"

#, python-format
msgid "PCI alias %(alias)s is not defined"
msgstr "PCI エイリアス %(alias)s が定義されていません"

#, python-format
msgid ""
"PCI device %(compute_node_id)s:%(address)s is %(status)s instead of "
"%(hopestatus)s"
msgstr ""
"PCI デバイス %(compute_node_id)s:%(address)s は %(hopestatus)s ではなく "
"%(status)s です"

#, python-format
msgid ""
"PCI device %(compute_node_id)s:%(address)s is owned by %(owner)s instead of "
"%(hopeowner)s"
msgstr ""
"PCI デバイス %(compute_node_id)s:%(address)s の所有者は、%(hopeowner)s ではな"
"く %(owner)s です"

#, python-format
msgid "PCI device %(id)s not found"
msgstr "PCI デバイス %(id)s が見つかりません"

#, python-format
msgid "PCI device request %(requests)s failed"
msgstr "PCI デバイス要求 %(requests)s が失敗しました"

#, python-format
msgid "Page size %(pagesize)s forbidden against '%(against)s'"
msgstr "ページサイズ %(pagesize)s は \"%(against)s\" に対して禁止されています"

#, python-format
msgid "Page size %(pagesize)s is not supported by the host."
msgstr "ページサイズ %(pagesize)s はこのホストではサポートされていません。"

#, python-format
msgid ""
"Parameters %(missing_params)s not present in vif_details for vif %(vif_id)s. "
"Check your Neutron configuration to validate that the macvtap parameters are "
"correct."
msgstr ""
"vif %(vif_id)s について、パラメーター %(missing_params)s が vif_details 内に"
"存在しません。macvtapパラーメーターが正確に設定されているか Neutron の設定を"
"確認してください。"

#, python-format
msgid "Path %s must be LVM logical volume"
msgstr "パス %s は LVM 論理ボリュームでなければなりません"

msgid "Paused"
msgstr "一時停止済み"

msgid "Personality file limit exceeded"
msgstr "パーソナリティーファイル数の上限を超えました"

#, python-format
msgid ""
"Physical Function %(compute_node_id)s:%(address)s, related to VF "
"%(compute_node_id)s:%(vf_address)s is %(status)s instead of %(hopestatus)s"
msgstr ""
"VF %(compute_node_id)s に関連する %(address)s のPhysical Function "
"%(compute_node_id)s。%(vf_address)s は %(status)s ではなく %(hopestatus)sです"

#, python-format
msgid "Physical network is missing for network %(network_uuid)s"
msgstr "ネットワーク %(network_uuid)s に対応する物理ネットワークがありません"

#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr "ポリシーにより %(action)s の実行が許可されていません"

#, python-format
msgid "Port %(port_id)s is still in use."
msgstr "ポート %(port_id)s はまだ使用中です。"

#, python-format
msgid "Port %(port_id)s not usable for instance %(instance)s."
msgstr "ポート %(port_id)s はインスタンス %(instance)s では使用できません。"

#, python-format
msgid ""
"Port %(port_id)s not usable for instance %(instance)s. Value %(value)s "
"assigned to dns_name attribute does not match instance's hostname "
"%(hostname)s"
msgstr ""
"ポート %(port_id)s はインスタンス %(instance)s では使用できません。dns_name "
"属性に割り当てられた値 %(value)s がインスタンスのホスト名 %(hostname)s と合致"
"しません"

#, python-format
msgid "Port %(port_id)s requires a FixedIP in order to be used."
msgstr "ポート %(port_id)s を使用するには、Fixed IP が必要です。"

#, python-format
msgid "Port %s is not attached"
msgstr "ポート %s は接続されていません"

#, python-format
msgid "Port id %(port_id)s could not be found."
msgstr "ポート ID %(port_id)s が見つかりませんでした。"

#, python-format
msgid "Provided video model (%(model)s) is not supported."
msgstr "指定されたビデオモデル (%(model)s) はサポートされていません。"

#, python-format
msgid "Provided watchdog action (%(action)s) is not supported."
msgstr ""
"指定されたウォッチドッグアクション (%(action)s) はサポートされていません。"

msgid "QEMU guest agent is not enabled"
msgstr "QEMU ゲストエージェントが有効になっていません"

#, python-format
msgid "Quiescing is not supported in instance %(instance_id)s"
msgstr "インスタンス %(instance_id)s を正常に終了することができません。"

#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr "クォータクラス %(class_name)s が見つかりませんでした。"

msgid "Quota could not be found"
msgstr "クォータが見つかりませんでした"

#, python-format
msgid ""
"Quota exceeded for %(overs)s: Requested %(req)s, but already used %(used)s "
"of %(allowed)s %(overs)s"
msgstr ""
"%(overs)s のクオータを超えました: %(req)s がリクエストされましたが、既に "
"%(allowed)s のうち %(used)s を使用しています (%(overs)s)"

#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr "リソース %(overs)s がクォータを超過しました"

msgid "Quota exceeded, too many key pairs."
msgstr "クォータを超過しました。キーペアが多すぎます。"

msgid "Quota exceeded, too many server groups."
msgstr "クォータを超過しました。サーバーグループが多すぎます。"

msgid "Quota exceeded, too many servers in group"
msgstr "クォータを超過しました。グループ内のサーバーが多すぎます"

#, python-format
msgid "Quota exists for project %(project_id)s, resource %(resource)s"
msgstr ""
"プロジェクト %(project_id)s、リソース %(resource)s のクォータが存在します"

#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr "プロジェクト %(project_id)s のクォータが見つかりませんでした。"

#, python-format
msgid ""
"Quota for user %(user_id)s in project %(project_id)s could not be found."
msgstr ""
"プロジェクト %(project_id)s のユーザー %(user_id)s のクォータが見つかりません"
"でした。"

#, python-format
msgid ""
"Quota limit %(limit)s for %(resource)s must be greater than or equal to "
"already used and reserved %(minimum)s."
msgstr ""
"%(resource)s のクォータ上限 %(limit)s は、既に使用もしくは予約されている数で"
"ある %(minimum)s 以上でなければなりません。"

#, python-format
msgid ""
"Quota limit %(limit)s for %(resource)s must be less than or equal to "
"%(maximum)s."
msgstr ""
"%(resource)s のクォータ上限 %(limit)s は、%(maximum)s 以下でなければなりませ"
"ん。"

msgid "Request body and URI mismatch"
msgstr "リクエスト本文と URI の不一致"

msgid "Request is too large."
msgstr "リクエストが大きすぎます。"

#, python-format
msgid "Request of image %(image_id)s got BadRequest response: %(response)s"
msgstr ""
"イメージ %(image_id)s のリクエストに対して BadRequest のレスポンスが返されま"
"した: %(response)s"

#, python-format
msgid "RequestSpec not found for instance %(instance_uuid)s"
msgstr "インスタンス %(instance_uuid)s に対する RequestSpec が見つかりません"

msgid "Requested CPU control policy not supported by host"
msgstr "ホストは要求された CPU の制御ポリシーをサポートしません"

#, python-format
msgid ""
"Requested hardware '%(model)s' is not supported by the '%(virt)s' virt driver"
msgstr ""
"要求されたハードウェア '%(model)s' は '%(virt)s' virt ドライバーではサポート"
"されません"

#, python-format
msgid "Requested image %(image)s has automatic disk resize disabled."
msgstr ""
"要求されたイメージ %(image)s ではディスクサイズの自動変更が無効になっていま"
"す。"

msgid ""
"Requested instance NUMA topology cannot fit the given host NUMA topology"
msgstr ""
"要求されたインスタンス NUMA トポロジーは、指定されたホスト NUMA トポロジーに"
"適合しません"

msgid ""
"Requested instance NUMA topology together with requested PCI devices cannot "
"fit the given host NUMA topology"
msgstr ""
"PCI デバイスとともに要求されたインスタンスの NUMA トポロジーは、指定されたホ"
"ストの NUMA トポロジーに適合できません"

#, python-format
msgid ""
"Requested vCPU limits %(sockets)d:%(cores)d:%(threads)d are impossible to "
"satisfy for vcpus count %(vcpus)d"
msgstr ""
"要求された vCPU 制限 %(sockets)d:%(cores)d:%(threads)d は、vCPU カウント "
"%(vcpus)d を満たすことができません"

#, python-format
msgid "Rescue device does not exist for instance %s"
msgstr "インスタンス %s 用のレスキューデバイスが存在しません"

#, python-format
msgid "Resize error: %(reason)s"
msgstr "サイズ変更エラー: %(reason)s"

msgid "Resize to zero disk flavor is not allowed."
msgstr "ディスクが 0 のフレーバーにサイズ変更することはできません。"

msgid "Resource could not be found."
msgstr "リソースを見つけられませんでした。"

msgid "Resumed"
msgstr "再開済み"

#, python-format
msgid "Root element name should be '%(name)s' not '%(tag)s'"
msgstr ""
"ルートエレメント名は '%(tag)s' ではなく '%(name)s' でなければなりません"

#, python-format
msgid "Running batches of %i until complete"
msgstr "完了するまで %i のバッチを実行します"

#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""
"スケジューラーホストフィルター %(filter_name)s が見つかりませんでした。"

#, python-format
msgid "Security group %(name)s is not found for project %(project)s"
msgstr ""
"プロジェクト %(project)s のセキュリティーグループ %(name)s が見つかりません"

#, python-format
msgid ""
"Security group %(security_group_id)s not found for project %(project_id)s."
msgstr ""
"プロジェクト %(project_id)s のセキュリティーグループ %(security_group_id)s が"
"見つかりません。"

#, python-format
msgid "Security group %(security_group_id)s not found."
msgstr "セキュリティーグループ %(security_group_id)s が見つかりません。"

#, python-format
msgid ""
"Security group %(security_group_name)s already exists for project "
"%(project_id)s."
msgstr ""
"プロジェクト %(project_id)s にはセキュリティーグループ "
"%(security_group_name)s がすでに存在します。"

#, python-format
msgid ""
"Security group %(security_group_name)s not associated with the instance "
"%(instance)s"
msgstr ""
"セキュリティーグループ %(security_group_name)s がインスタンス %(instance)s に"
"関連付けられていません"

msgid "Security group id should be uuid"
msgstr "セキュリティーグループ ID は UUID でなければなりません"

msgid "Security group name cannot be empty"
msgstr "セキュリティーグループ名を空にすることはできません"

msgid "Security group not specified"
msgstr "セキュリティーグループが指定されていません"

#, python-format
msgid "Server disk was unable to be resized because: %(reason)s"
msgstr "サーバーディスクのサイズを変更できませんでした。理由: %(reason)s"

msgid "Server does not exist"
msgstr "サーバーが存在しません。"

#, python-format
msgid "ServerGroup policy is not supported: %(reason)s"
msgstr "サーバーグループポリシーはサポートされていません: %(reason)s"

msgid "ServerGroupAffinityFilter not configured"
msgstr "ServerGroupAffinityFilter が設定されていません"

msgid "ServerGroupAntiAffinityFilter not configured"
msgstr "ServerGroupAntiAffinityFilter が設定されていません"

msgid "ServerGroupSoftAffinityWeigher not configured"
msgstr "ServerGroupSoftAffinityWeigher が設定されていません"

msgid "ServerGroupSoftAntiAffinityWeigher not configured"
msgstr "ServerGroupSoftAntiAffinityWeigher が設定されていません"

#, python-format
msgid "Service %(service_id)s could not be found."
msgstr "サービス %(service_id)s が見つかりませんでした。"

#, python-format
msgid "Service %s not found."
msgstr "サービス %s が見つかりません。"

msgid "Service is unavailable at this time."
msgstr "サービスが現在利用できません。"

#, python-format
msgid "Service with host %(host)s binary %(binary)s exists."
msgstr ""
"ホスト %(host)s のバイナリー %(binary)s を使用するサービスが存在します。"

#, python-format
msgid "Service with host %(host)s topic %(topic)s exists."
msgstr "ホスト %(host)s のトピック %(topic)s を使用するサービスが存在します。"

msgid "Set admin password is not supported"
msgstr "設定された管理者パスワードがサポートされません"

#, python-format
msgid "Share '%s' is not supported"
msgstr "シェア '%s' はサポートされません"

#, python-format
msgid "Share level '%s' cannot have share configured"
msgstr "シェアレベル '%s' に設定されたシェアがありません"

#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr "スナップショット %(snapshot_id)s が見つかりませんでした。"

msgid "Some required fields are missing"
msgstr "いくつかの必須フィールドがありません。"

#, python-format
msgid ""
"Something went wrong when deleting a volume snapshot: rebasing a "
"%(protocol)s network disk using qemu-img has not been fully tested"
msgstr ""
"ボリュームのスナップショットの削除中に問題が発生しました: qemu-img を使用し"
"て %(protocol)s のネットワークディスクを再設定することは十分に検証されていま"
"せん。"

msgid "Sort direction size exceeds sort key size"
msgstr "ソート方向の数がソートキーの数より多いです"

msgid "Sort key supplied was not valid."
msgstr "指定されたソートキーが無効でした。"

msgid "Specified fixed address not assigned to instance"
msgstr "指定された固定アドレスはインスタンスに割り当てられていません"

msgid "Started"
msgstr "開始済み"

msgid "Stopped"
msgstr "停止済み"

#, python-format
msgid "Storage error: %(reason)s"
msgstr "ストレージエラー: %(reason)s"

#, python-format
msgid "Storage policy %s did not match any datastores"
msgstr "ストレージポリシー %s がどのデータストアにも一致しませんでした"

msgid "Success"
msgstr "成功"

msgid "Suspended"
msgstr "休止済み"

msgid "Swap drive requested is larger than instance type allows."
msgstr ""
"要求されたスワップドライブのサイズが、インスタンスタイプで許可されているサイ"
"ズを超えています。"

msgid "Table"
msgstr "テーブル"

#, python-format
msgid "Task %(task_name)s is already running on host %(host)s"
msgstr "タスク %(task_name)s はホスト %(host)s 上で既に実行中です"

#, python-format
msgid "Task %(task_name)s is not running on host %(host)s"
msgstr "タスク %(task_name)s はホスト %(host)s 上で実行されていません"

#, python-format
msgid "The PCI address %(address)s has an incorrect format."
msgstr "PCI アドレス %(address)s の形式が正しくありません。"

msgid "The backlog must be more than 0"
msgstr "バックログは 0 より大きい値である必要があります"

#, python-format
msgid "The console port range %(min_port)d-%(max_port)d is exhausted."
msgstr ""
"コンソール用のポート範囲 %(min_port)d-%(max_port)d を使い切られています。"

msgid "The created instance's disk would be too small."
msgstr "作成されたインスタンスのディスクが小さすぎます。"

msgid "The current driver does not support preserving ephemeral partitions."
msgstr "現行ドライバーは、一時パーティションの保持をサポートしていません。"

msgid "The default PBM policy doesn't exist on the backend."
msgstr "デフォルト PBM ポリシーがバックエンドに存在しません。"

msgid "The floating IP request failed with a BadRequest"
msgstr "Floating IP のリクエストが BadRequest により失敗しました。"

msgid ""
"The instance requires a newer hypervisor version than has been provided."
msgstr ""
"このインスタンスは使用されているものよりも新しいバージョンのハイパーバイザー"
"を必要とします。"

#, python-format
msgid "The number of defined ports: %(ports)d is over the limit: %(quota)d"
msgstr "定義したポート %(ports)d の数が上限 %(quota)d を超えています"

#, python-format
msgid "The provided RNG device path: (%(path)s) is not present on the host."
msgstr "指定された RNG デバイスパス (%(path)s) がホスト上にありません。"

msgid "The request body can't be empty"
msgstr "リクエスト本文は空にはできません"

msgid "The request is invalid."
msgstr "リクエスト内容が無効です。"

#, python-format
msgid ""
"The requested amount of video memory %(req_vram)d is higher than the maximum "
"allowed by flavor %(max_vram)d."
msgstr ""
"要求されたビデオメモリー容量 %(req_vram)d がフレーバー %(max_vram)d で許可さ"
"れている最大値を上回っています。"

msgid "The requested availability zone is not available"
msgstr "要求されたアベイラビリティーゾーンは使用不可です"

msgid "The requested console type details are not accessible"
msgstr "要求されたコンソールタイプの詳細にはアクセスできません"

msgid "The requested functionality is not supported."
msgstr "要求された機能はサポートされていません。"

#, python-format
msgid "The specified cluster '%s' was not found in vCenter"
msgstr "指定されたクラスター '%s' が vCenter で見つかりませんでした"

#, python-format
msgid "The supplied device path (%(path)s) is in use."
msgstr "指定されたデバイスパス (%(path)s) は使用中です。"

#, python-format
msgid "The supplied device path (%(path)s) is invalid."
msgstr "指定されたデバイスパス (%(path)s) が無効です。"

#, python-format
msgid ""
"The supplied disk path (%(path)s) already exists, it is expected not to "
"exist."
msgstr ""
"指定されたディスクパス (%(path)s) は既にに存在します。これは存在しているべき"
"ではありません。"

msgid "The supplied hypervisor type of is invalid."
msgstr "指定されたハイパーバイザーは無効です。"

msgid "The target host can't be the same one."
msgstr "宛先ホストを同じホストにすることはできません。"

#, python-format
msgid "The token '%(token)s' is invalid or has expired"
msgstr "トークン \"%(token)s\" が無効か、有効期限切れです"

#, python-format
msgid ""
"The volume cannot be assigned the same device name as the root device %s"
msgstr ""
"ボリュームにルートデバイス %s と同じデバイス名を割り当てることはできません"

msgid "There are not enough hosts available."
msgstr "使用可能なホストが不足しています。"

#, python-format
msgid "There is no such action: %s"
msgstr "このようなアクションはありません: %s"

#, python-format
msgid ""
"This compute node's hypervisor is older than the minimum supported version: "
"%(version)s."
msgstr ""
"このコンピュートノードのハイパーバイザーがサポートされる最小バージョンよりも"
"古くなっています: %(version)s。"

msgid ""
"This method needs to be called with either networks=None and port_ids=None "
"or port_ids and networks as not none."
msgstr ""
"このメソッドを呼び出すには、networks と port_ids に None を設定するか、 "
"port_ids と networks に None 以外の値を設定する必要があります。"

#, python-format
msgid "This rule already exists in group %s"
msgstr "指定されたルールは既にグループ %s に存在しています。"

#, python-format
msgid ""
"This service is older (v%(thisver)i) than the minimum (v%(minver)i) version "
"of the rest of the deployment. Unable to continue."
msgstr ""
"このサービスが実装環境の残りの部分の最小 (v%(minver)i) バージョンよりも古く "
"(v%(thisver)i) なっています。処理を継続できません。"

msgid "Timeout waiting for response from cell"
msgstr "セルからの応答を待機中にタイムアウトになりました"

#, python-format
msgid "Timeout while checking if we can live migrate to host: %s"
msgstr ""
"ホスト %s にライブマイグレーションできるか確認中にタイムアウトが発生しました"

msgid "To and From ports must be integers"
msgstr "開始ポートと終了ポートは整数でなければなりません"

msgid "Token not found"
msgstr "トークンが見つかりません"

msgid "Triggering crash dump is not supported"
msgstr "クラッシュダンプのトリガーはサポートされません"

msgid "Type and Code must be integers for ICMP protocol type"
msgstr "ICMP プロトコルのタイプおよびコードは整数でなければなりません"

msgid "UEFI is not supported"
msgstr "UEFI はサポートされません"

#, python-format
msgid ""
"Unable to associate floating IP %(address)s to any fixed IPs for instance "
"%(id)s. Instance has no fixed IPv4 addresses to associate."
msgstr ""
"インスタンス %(id)s において Floating IP %(address)s を Fixed IP に割り当てる"
"ことができません。インスタンスに割り当てを行うべき Fixed IPv4 がありません。"

#, python-format
msgid ""
"Unable to associate floating IP %(address)s to fixed IP %(fixed_address)s "
"for instance %(id)s. Error: %(error)s"
msgstr ""
"インスタンス %(id)s において Floating IP %(address)s を Fixed IP "
"%(fixed_address)s に割り当てることができません。エラー: %(error)s"

#, python-format
msgid "Unable to convert image to %(format)s: %(exp)s"
msgstr "イメージを %(format)s に変換できません: %(exp)s"

#, python-format
msgid "Unable to convert image to raw: %(exp)s"
msgstr "イメージを raw 形式に変換できません: %(exp)s"

#, python-format
msgid "Unable to determine disk bus for '%s'"
msgstr "ディスク '%s' のバスを判別できません"

#, python-format
msgid "Unable to determine disk prefix for %s"
msgstr "%s のディスクプレフィックスを判別できません"

#, python-format
msgid "Unable to find ca_file : %s"
msgstr "ca_file が見つかりません: %s"

#, python-format
msgid "Unable to find cert_file : %s"
msgstr "cert_file が見つかりません: %s"

#, python-format
msgid "Unable to find host for Instance %s"
msgstr "インスタンス %s のホストが見つかりません"

msgid "Unable to find iSCSI Target"
msgstr "iSCSI ターゲットが見つかりません"

#, python-format
msgid "Unable to find key_file : %s"
msgstr "key_file %s が見つかりません"

msgid "Unable to find volume"
msgstr "ボリュームが見つかりません"

msgid "Unable to get host UUID: /etc/machine-id does not exist"
msgstr " ホストの UUID を取得できません: /etc/machine-id が存在しません"

msgid "Unable to get host UUID: /etc/machine-id is empty"
msgstr "ホストの UUID が取得できません: /etc/machine-id が空です"

msgid ""
"Unable to launch multiple instances with a single configured port ID. Please "
"launch your instance one by one with different ports."
msgstr ""
"1個の作成済みのポート ID で複数のインスタンスの起動はできません。1 つ 1 つの"
"インスタンスを別々のポートで起動してください。"

#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s to %(dest)s: Lack of memory(host:"
"%(avail)s <= instance:%(mem_inst)s)"
msgstr ""
"%(instance_uuid)s を %(dest)s にマイグレーションできません: メモリー不足です "
"(host:%(avail)s <= instance:%(mem_inst)s)"

#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s: Disk of instance is too large(available "
"on destination host:%(available)s < need:%(necessary)s)"
msgstr ""
"%(instance_uuid)s をマイグレーションできません: インスタンスのディスクが大き"
"すぎます (宛先ホスト上の使用可能量: %(available)s < 必要量: %(necessary)s)"

#, python-format
msgid ""
"Unable to migrate instance (%(instance_id)s) to current host (%(host)s)."
msgstr ""
"インスタンス (%(instance_id)s) を現在と同じホスト (%(host)s) にマイグレーショ"
"ンすることはできません。"

msgid "Unable to resize disk down."
msgstr "ディスクのサイズを縮小することができません。"

msgid "Unable to set password on instance"
msgstr "インスタンスにパスワードを設定できません"

msgid "Unable to shrink disk."
msgstr "ディスクを縮小できません。"

#, python-format
msgid "Unacceptable CPU info: %(reason)s"
msgstr "指定できない CPU 情報: %(reason)s"

msgid "Unacceptable parameters."
msgstr "指定できないパラメーターです。"

#, python-format
msgid "Unavailable console type %(console_type)s."
msgstr "コンソールタイプ %(console_type)s は使用できません。"

msgid ""
"Undefined Block Device Mapping root: BlockDeviceMappingList contains Block "
"Device Mappings from multiple instances."
msgstr ""
"ブロックデバイスマッピングのルートが定義されていません: "
"BlockDeviceMappingList に複数のインスタンスのブロックデバイスのマッピングが含"
"まれています。"

#, python-format
msgid "Unexpected aggregate action %s"
msgstr "想定しないアグリゲートのアクション %s"

msgid "Unexpected type adding stats"
msgstr "統計の追加中に想定しないタイプが見つかりました"

#, python-format
msgid "Unexpected vif_type=%s"
msgstr "想定しない vif_type=%s"

msgid "Unknown"
msgstr "不明"

msgid "Unknown action"
msgstr "不明なアクション"

#, python-format
msgid "Unknown config drive format %(format)s. Select one of iso9660 or vfat."
msgstr ""
"不明なコンフィグドライブ形式 %(format)s です。「iso9660」または「vfat」のいず"
"れかを選択してください。"

#, python-format
msgid "Unknown delete_info type %s"
msgstr "不明な delete_info タイプ %s"

#, python-format
msgid "Unknown image_type=%s"
msgstr "不明な image_type=%s"

#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr "不明なクォータリソース %(unknown)s。"

msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "ソート方向が不明です。'desc' または 'asc' でなければなりません"

#, python-format
msgid "Unknown type: %s"
msgstr "不明なタイプ: %s"

msgid "Unrecognized legacy format."
msgstr "認識できない以前のフォーマットです。"

#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr "認識されない read_deleted 値 '%s'"

#, python-format
msgid "Unrecognized value '%s' for CONF.running_deleted_instance_action"
msgstr "CONF.running_deleted_instance_action で認識されない値 '%s'"

#, python-format
msgid "Unshelve attempted but the image %s cannot be found."
msgstr "復元が試行されましたが、イメージ %s が見つかりません。"

msgid "Unsupported Content-Type"
msgstr "サポートされない Content-Type"

#, python-format
msgid "User %(username)s not found in password file."
msgstr "パスワードファイルにユーザー %(username)s が見つかりません。"

#, python-format
msgid "User %(username)s not found in shadow file."
msgstr "shadow ファイルにユーザー %(username)s が見つかりません。"

msgid "User data needs to be valid base 64."
msgstr "ユーザーデータは有効な Base64 でなければなりません。"

msgid "User does not have admin privileges"
msgstr "ユーザーに管理者権限がありません"

msgid ""
"Using different block_device_mapping syntaxes is not allowed in the same "
"request."
msgstr "同じリクエスト内で異なる block_device_mapping 指定は使用できません。"

#, python-format
msgid ""
"Version %(req_ver)s is not supported by the API. Minimum is %(min_ver)s and "
"maximum is %(max_ver)s."
msgstr ""
"バージョン %(req_ver)s はこの API ではサポートされていません。最小"
"は%(min_ver)s、最大は %(max_ver)s です。"

msgid "Virtual Interface creation failed"
msgstr "仮想インターフェースの作成に失敗しました"

msgid "Virtual interface plugin failed"
msgstr "仮想インターフェースの接続に失敗しました"

#, python-format
msgid "Virtual machine mode '%(vmmode)s' is not recognised"
msgstr "仮想マシンモード '%(vmmode)s' は認識できません"

#, python-format
msgid "Virtual machine mode '%s' is not valid"
msgstr "仮想マシンモード '%s' が有効ではありません"

#, python-format
msgid "Virtualization type '%(virt)s' is not supported by this compute driver"
msgstr ""
"このコンピュートドライバーでは仮想化タイプ '%(virt)s' はサポートされません"

#, python-format
msgid "Volume %(volume_id)s could not be attached. Reason: %(reason)s"
msgstr "ボリューム %(volume_id)s を接続できません。理由: %(reason)s"

#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr "ボリューム %(volume_id)s が見つかりませんでした。"

#, python-format
msgid ""
"Volume %(volume_id)s did not finish being created even after we waited "
"%(seconds)s seconds or %(attempts)s attempts. And its status is "
"%(volume_status)s."
msgstr ""
"%(seconds)s 秒待機し、%(attempts)s 回試行したものの、ボリューム "
"%(volume_id)s を作成することができませんでした。状況は %(volume_status)s で"
"す。"

msgid "Volume does not belong to the requested instance."
msgstr "ボリュームが要求されたインスタンスに属していません。"

#, python-format
msgid ""
"Volume encryption is not supported for %(volume_type)s volume %(volume_id)s"
msgstr ""
"%(volume_type)s のボリューム %(volume_id)s に関してボリュームの暗号化はサポー"
"トされません。"

#, python-format
msgid ""
"Volume is smaller than the minimum size specified in image metadata. Volume "
"size is %(volume_size)i bytes, minimum size is %(image_min_disk)i bytes."
msgstr ""
"ボリュームがイメージのメタデータで指定された最小サイズよりも小さくなっていま"
"す。ボリュームサイズは %(volume_size)i バイト、最小サイズは "
"%(image_min_disk)i バイトです。"

#, python-format
msgid ""
"Volume sets block size, but the current libvirt hypervisor '%s' does not "
"support custom block size"
msgstr ""
"ボリュームによってブロックサイズが設定されますが、現在の libvirt ハイパーバイ"
"ザー '%s' はカスタムブロックサイズをサポートしていません"

msgid "When resizing, instances must change flavor!"
msgstr "サイズ変更の際は、インスタンスのフレーバーを変更する必要があります。"

msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"サーバーを SSL モードで実行する場合は、設定ファイルで cert_file と key_file "
"の両方のオプションに値を指定する必要があります"

#, python-format
msgid "Wrong quota method %(method)s used on resource %(res)s"
msgstr ""
"リソース %(res)s で使用されるクォータメソッド %(method)s が正しくありません"

msgid "X-Forwarded-For is missing from request."
msgstr "リクエストに X-Forwarded-For がありません。"

msgid "X-Instance-ID header is missing from request."
msgstr "リクエストに X-Instance-ID ヘッダーがありません。"

msgid "X-Instance-ID-Signature header is missing from request."
msgstr "X-Instance-ID-Signature ヘッダーがリクエストにありません。"

msgid "X-Metadata-Provider is missing from request."
msgstr "リクエストに X-Metadata-Provider がありません。"

msgid "X-Tenant-ID header is missing from request."
msgstr "リクエストに X-Tenant-ID ヘッダーがありません。"

msgid "You are not allowed to delete the image."
msgstr "このイメージの削除は許可されていません。"

msgid ""
"You are not authorized to access the image the instance was started with."
msgstr ""
"インスタンスの起動時に使用されたイメージへのアクセスが許可されていません。"

msgid "You must implement __call__"
msgstr "__call__ を実装しなければなりません"

msgid "You should specify images_rbd_pool flag to use rbd images."
msgstr ""
"rbd イメージを使用するには images_rbd_pool フラグを指定する必要があります。"

msgid "You should specify images_volume_group flag to use LVM images."
msgstr ""
"LVM イメージを使用するには images_volume_group フラグを指定する必要がありま"
"す。"

msgid "Zero floating IPs available."
msgstr "使用可能な Floating IP はありません。"

msgid "admin password can't be changed on existing disk"
msgstr "既存のディスク上で管理者パスワードを変更することはできません"

msgid "cannot understand JSON"
msgstr "JSON を解釈できません"

msgid "clone() is not implemented"
msgstr "clone() は実装されていません"

#, python-format
msgid "connect info: %s"
msgstr "接続情報: %s"

#, python-format
msgid "connecting to: %(host)s:%(port)s"
msgstr "%(host)s:%(port)s に接続中です"

msgid "direct_snapshot() is not implemented"
msgstr "direct_snapshot() が実装されていません"

#, python-format
msgid "disk type '%s' not supported"
msgstr "ディスクタイプ '%s' はサポートされていません"

#, python-format
msgid "empty project id for instance %s"
msgstr "インスタンス %s のプロジェクト ID が空です"

msgid "error setting admin password"
msgstr "管理者パスワードの設定中にエラーが発生しました"

#, python-format
msgid "error: %s"
msgstr "エラー: %s"

#, python-format
msgid "failed to generate X509 fingerprint. Error message: %s"
msgstr "X.509 フィンガープリントの生成に失敗しました。エラーメッセージ: %s"

msgid "failed to generate fingerprint"
msgstr "フィンガープリントの生成に失敗しました"

msgid "filename cannot be None"
msgstr "ファイル名を None にすることはできません"

msgid "floating IP is already associated"
msgstr "Floating IP は既に割り当てられています"

msgid "floating IP not found"
msgstr "Floating IP が見つかりません"

#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr "fmt=%(fmt)s は %(backing_file)s でサポートされています"

#, python-format
msgid "href %s does not contain version"
msgstr "href %s にバージョンが含まれていません"

msgid "image already mounted"
msgstr "イメージは既にマウントされています"

#, python-format
msgid "instance %s is not running"
msgstr "インスタンス %s は実行されていません"

msgid "instance is a required argument to use @refresh_cache"
msgstr "@refresh_cache を使用する場合、インスタンスは必須の引数です"

msgid "instance is not in a suspended state"
msgstr "インスタンスは休止状態ではありません"

msgid "instance is not powered on"
msgstr "インスタンスの電源がオンになっていません"

msgid "instance is powered off and cannot be suspended."
msgstr "インスタンスは電源オフになっています。休止できません。"

#, python-format
msgid "instance_id %s could not be found as device id on any ports"
msgstr "instance_id %s がデバイス ID に設定されたポートが見つかりませんでした"

msgid "is_public must be a boolean"
msgstr "is_public はブール値でなければなりません"

msgid "keymgr.fixed_key not defined"
msgstr "keymgr.fixed_key が定義されていません"

msgid "l3driver call to add floating IP failed"
msgstr "Floating IP を追加するための l3driver の呼び出しが失敗しました"

#, python-format
msgid "libguestfs installed but not usable (%s)"
msgstr "libguestfs はインストールされていますが、使用できません (%s)"

#, python-format
msgid "libguestfs is not installed (%s)"
msgstr "libguestfs がインストールされていません (%s)"

#, python-format
msgid "marker [%s] not found"
msgstr "マーカー [%s] が見つかりません"

#, python-format
msgid "max rows must be <= %(max_value)d"
msgstr "最大行数は %(max_value)d 以上である必要があります"

msgid "max_count cannot be greater than 1 if an fixed_ip is specified."
msgstr ""
"fixed_ip が指定されている場合、max_count を 1 より大きくすることはできませ"
"ん。"

msgid "min_count must be <= max_count"
msgstr "min_count は max_count 以下でなければなりません"

#, python-format
msgid "nbd device %s did not show up"
msgstr "nbd デバイス %s が出現しません"

msgid "nbd unavailable: module not loaded"
msgstr "nbd が使用不可です: モジュールがロードされていません"

#, python-format
msgid "no match found for %s"
msgstr "%s に合致するものが見つかりません"

#, python-format
msgid "no usable parent snapshot for volume %s"
msgstr "ボリューム %s に関して使用可能な親スナップショットがありません"

#, python-format
msgid "no write permission on storage pool %s"
msgstr "ストレージプール %s に書き込み権限がありません"

#, python-format
msgid "not able to execute ssh command: %s"
msgstr "ssh コマンドを実行できません: %s"

msgid "old style configuration can use only dictionary or memcached backends"
msgstr ""
"古い形式の設定では、ディクショナリーと memcached のバックエンドのみを使用でき"
"ます"

msgid "operation time out"
msgstr "操作がタイムアウトしました"

#, python-format
msgid "partition %s not found"
msgstr "パーティション %s が見つかりません"

#, python-format
msgid "partition search unsupported with %s"
msgstr "パーティションの検索は %s ではサポートされていません"

msgid "pause not supported for vmwareapi"
msgstr "vmwareapi では一時停止はサポートされていません"

msgid "printable characters with at least one non space character"
msgstr "1 つ以上のスペースではない文字を含む印刷可能な文字。"

msgid "printable characters. Can not start or end with whitespace."
msgstr "印刷可能な文字。空白で開始または終了することはできません。"

#, python-format
msgid "qemu-img failed to execute on %(path)s : %(exp)s"
msgstr "%(path)s で qemu-img を実行できませんでした: %(exp)s"

#, python-format
msgid "qemu-nbd error: %s"
msgstr "qemu-nbd エラー: %s"

msgid "rbd python libraries not found"
msgstr "rbd python ライブラリーが見つかりません"

#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""
"read_deleted に指定できるのは 'no', 'yes', 'only' のいずれかです。%r は指定で"
"きません。"

msgid "serve() can only be called once"
msgstr "serve() は一度しか呼び出せません"

msgid "service is a mandatory argument for DB based ServiceGroup driver"
msgstr "サービスは DB ベースの ServiceGroup ドライバーの必須の引数です"

msgid "service is a mandatory argument for Memcached based ServiceGroup driver"
msgstr "service は Memcached ベースの ServiceGroup ドライバーの必須の引数です"

msgid "set_admin_password is not implemented by this driver or guest instance."
msgstr ""
"set_admin_password は、このドライバーまたはゲストインスタンスでは実装されてい"
"ません。"

#, python-format
msgid "snapshot for %s"
msgstr "%s のスナップショット"

msgid "snapshot_id required in create_info"
msgstr "create_info には snapshot_id が必要です"

msgid "token not provided"
msgstr "トークンが指定されていません"

msgid "too many body keys"
msgstr "本文にキーが多すぎます"

msgid "unpause not supported for vmwareapi"
msgstr "vmwareapi では一時停止解除はサポートされていません"

#, python-format
msgid "vg %s must be LVM volume group"
msgstr "vg %s は LVM ボリュームグループでなければなりません"

#, python-format
msgid "vhostuser_sock_path not present in vif_details for vif %(vif_id)s"
msgstr "vhostuser_sock_path が vif %(vif_id)s の vif_details にありません"

#, python-format
msgid "vif type %s not supported"
msgstr "vif タイプ %s はサポートされません"

msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr "この vif_driver の実装では vif_type パラメーターが必要です"

#, python-format
msgid "volume %s already attached"
msgstr "ボリューム %s は既に接続されています"

#, python-format
msgid ""
"volume '%(vol)s' status must be 'in-use'. Currently in '%(status)s' status"
msgstr ""
"ボリューム '%(vol)s' の状況は「使用中」でなければなりませんが、現在の状況は "
"'%(status)s' です"
